version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
    backend:
        build:
            context: ./  # Path to your backend Dockerfile
            dockerfile: ./back/Dockerfile
        container_name: fastapi_backend
        ports:
            - "8000:8000"
        networks:
            - app-tier
        depends_on:
            - db
    db:
        image: 'mongo'
        restart: always
        ports:
            - "27017-27019:27017-27019"
        expose:
            - 27017-27019
        environment:
            - MONGO_INITDB_DATABASE=${MONGODB_DATABASE_NAME}
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PWD}
            - MONGODB_USER=${MONGODB_USER}
            - MONGODB_PASSWORD=${MONGODB_PASSWORD}
            - MONGODB_TEST_DATABASE_NAME=${MONGODB_TEST_DATABASE_NAME}
        networks:
            - app-tier 
        volumes:
            # - ./mongo-volume:/data/db
            - ./back/ops/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    frontend:
        build:
            context: ./front 
        container_name: angular_frontend
        ports:
            - "8100:80"
        networks:
            - app-tier
        depends_on:
            - backend
        expose:
            - 8100
        restart: always

